config/routes.rb
TodoApp::Application.routes.draw do
  resource :session
  get 'projects', to: redirect('/')
  resources :projects do
    resources :todos do
      member do
        patch :complete
      end
    end
  end
  root to: 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :todos, dependent: :delete_all
  belongs_to :user, touch: true

  def new_todo(*args, &block)
    todos.build(*args, &block)
  end

  def all_todos
    todos.order(:created_at).all
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :desc, presence: true, hashtag: true, length: 4..1000
  belongs_to :project, touch: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
  before_action :set_user
  before_action :authentication_required

  private

  def authentication_required
    unless current_user
      redirect_to new_session_path
    end
  end

  def set_user
    @current_user = User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
  end

  attr_reader :current_user

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.includes(:todos).find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :desc)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authentication_required, only: [:new, :create]

  # Login Form
  def new
  end

  # Login
  def create
    user = User.find_by email: params[:email]
    if user && user.authenticate(params[:password])
      cookies.signed.permanent[:user_id] = user.id
      redirect_to root_url
    else
      render :new
    end
  end

  # Logout
  def destroy
    cookies.signed.permanent[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_project
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :complete]

  # GET /todos
  # GET /todos.json
  def index
    @todos = @project.all_todos
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = @project.new_todo
  end

  # GET /todos/1/edit
  def edit
  end

  def complete
    @todo.update done: params[:checked]
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { render json: { OK: true } }
    end
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = @project.new_todo(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to [@project, @todo], notice: 'Todo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to [@project, @todo], notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@project) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = current_user.projects.find(params[:project_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = @project.todos.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_params
    params.require(:todo).permit(:desc, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  attr_reader :current_user
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
<% if current_user %>
  <%= current_user.email %>
  <%= link_to "Logout", session_path, method: :delete %>
<% end %>

<%= yield %>
</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.desc %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @project.desc %>
</p>

<%= form_for [@project, Todo.new], data: { new_todo: true } do |f| %>
  <%= f.text_field :desc %>
  <%= f.submit "Add" %>
<% end %>

<%= render "todos/todos", project: @project, todos: @project.todos.to_a.sort { |a,b| a.created_at <=> b.created_at } %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/_todos.html.erb
<ul>
  <% todos.each do |todo| %>
    <li>
      <%= label_tag nil do %>
        <%= check_box_tag "done_#{todo.id}", 1, todo.done, data: { sync: complete_project_todo_path(project, todo, format: 'json') } %>
        <%= todo.desc %>
      <% end %>
      <%= link_to "edit", edit_project_todo_path(project, todo) %>
      <%= link_to 'destroy', project_todo_path(project, todo), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<% @todos.each do |todo| %>
  <li>
    <%= check_box_tag :done, 1, todo.done, data: { sync: complete_todo_path(todo, format: 'json') } %>
    <%= label_tag :done, todo.desc %>
    <%= link_to "edit", edit_todo_path(todo) %>
    <%= link_to 'destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %>
  </li>
<% end %>

<p>
  <%= link_to 'New Todo', new_todo_path %>
</p>

app/views/todos/new.html.erb
<h1><%= t(".title") %></h1>

<%= render 'form' %>

<%= link_to t("shared.back"), todos_path %>

app/views/todos/show.html.erb
<li>
  <%= label_tag nil do %>
    <%= check_box_tag "done_#{@todo.id}", 1, @todo.done, data: { sync: complete_project_todo_path(@project, @todo, format: 'json') } %>
    <%= @todo.desc %>
  <% end %>
  <%= link_to "edit", edit_project_todo_path(@project, @todo) %>
  <%= link_to 'destroy', project_todo_path(@project, @todo), method: :delete, data: { confirm: 'Are you sure?' } %>
</li>